// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using conectabairro.Models;

#nullable disable

namespace conectabairro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122113920_AdicionarSolicitacoes")]
    partial class AdicionarSolicitacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("conectabairro.Models.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<int>("AutorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("PostId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("conectabairro.Models.Conversa", b =>
                {
                    b.Property<int>("ConversaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversaId"));

                    b.Property<int>("AutorPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("InteressadoUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversaId");

                    b.HasIndex("AutorPostId");

                    b.HasIndex("InteressadoUsuarioId");

                    b.HasIndex("PostId", "AutorPostId", "InteressadoUsuarioId")
                        .IsUnique();

                    b.ToTable("Conversas");
                });

            modelBuilder.Entity("conectabairro.Models.Mensagem", b =>
                {
                    b.Property<int>("MensagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensagemId"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<int>("RemetenteUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MensagemId");

                    b.HasIndex("ConversaId");

                    b.HasIndex("RemetenteUsuarioId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("conectabairro.Models.Posts", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("CaminhoImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DislikesCount")
                        .HasColumnType("int");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PostId");

                    b.HasIndex("AutorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("conectabairro.Models.Reacao", b =>
                {
                    b.Property<int>("ReacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReacaoId"));

                    b.Property<int>("AutorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TipoReacao")
                        .HasColumnType("int");

                    b.HasKey("ReacaoId");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("PostId", "AutorUsuarioId")
                        .IsUnique();

                    b.ToTable("Reacao");
                });

            modelBuilder.Entity("conectabairro.Models.SolicitacaoEdicao", b =>
                {
                    b.Property<int>("SolicitacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitacaoId"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NovaCidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovaRua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovoBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovoEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SolicitacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitacoesEdicao");
                });

            modelBuilder.Entity("conectabairro.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarios")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Bairro = "N/A",
                            Cidade = "N/A",
                            Email = "admin@a",
                            Estado = "N/A",
                            Nome = "Administrador Geral",
                            PasswordHash = "$2a$13$Gn3F7qkrzVWosndLaiRD6OzWWZrWfjCFNzTI2R4/6FAwy2BV2ZkTu",
                            Rua = "N/A",
                            Telefone = "",
                            TipoUsuarios = 0
                        });
                });

            modelBuilder.Entity("conectabairro.Models.Comentario", b =>
                {
                    b.HasOne("conectabairro.Models.Usuario", "Autor")
                        .WithMany("ComentariosFeitos")
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("conectabairro.Models.Posts", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("conectabairro.Models.Conversa", b =>
                {
                    b.HasOne("conectabairro.Models.Usuario", "AutorPost")
                        .WithMany("ConversasIniciadas")
                        .HasForeignKey("AutorPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("conectabairro.Models.Usuario", "Interessado")
                        .WithMany()
                        .HasForeignKey("InteressadoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("conectabairro.Models.Posts", "Post")
                        .WithMany("Conversas")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorPost");

                    b.Navigation("Interessado");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("conectabairro.Models.Mensagem", b =>
                {
                    b.HasOne("conectabairro.Models.Conversa", "Conversa")
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("conectabairro.Models.Usuario", "Remetente")
                        .WithMany("MensagensEnviadas")
                        .HasForeignKey("RemetenteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversa");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("conectabairro.Models.Posts", b =>
                {
                    b.HasOne("conectabairro.Models.Usuario", "Usuario")
                        .WithMany("PostsCriados")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("conectabairro.Models.Reacao", b =>
                {
                    b.HasOne("conectabairro.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("conectabairro.Models.Posts", "Post")
                        .WithMany("Reacoes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("conectabairro.Models.SolicitacaoEdicao", b =>
                {
                    b.HasOne("conectabairro.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("conectabairro.Models.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("conectabairro.Models.Posts", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Conversas");

                    b.Navigation("Reacoes");
                });

            modelBuilder.Entity("conectabairro.Models.Usuario", b =>
                {
                    b.Navigation("ComentariosFeitos");

                    b.Navigation("ConversasIniciadas");

                    b.Navigation("MensagensEnviadas");

                    b.Navigation("PostsCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
